---
# tasks file for ldaptoolbox

- name: debian repository
  block:

  - name: import repository key
    apt_key:
      url: "{{ ldaptoolbox_apt_key_url }}"
      id: "{{ ldaptoolbox_apt_key_id }}"
      validate_certs: "{{ ldaptoolbox_validate_certs }}"
      state: present
  
  - name: add repository
    apt_repository:
      repo: "{{ ldaptoolbox_apt_repo }}"
      filename: "{{ ldaptoolbox_apt_repo_filename }}"
      update_cache: yes
      state: present
    #ignore_errors: true

  when:
  - ansible_os_family == "Debian"


- name: centos repository
  block:

  - name: fetch repository key
    ansible.builtin.shell: "rpm --import https://ltb-project.org/documentation/_static/RPM-GPG-KEY-LTB-project"

  - name: setup epel repository
    ansible.builtin.shell: |
      dnf config-manager --set-enabled powertools
      dnf install -y epel-release epel-next-release

  - name: "setup ldaptoolbox repository on redhat / centos / rocky "
    copy:
      content: |
        [ltb-project]
        name=LTB project packages
        baseurl={{ ldaptoolbox_rpm_repo_baseurl }}
        enabled=1
        gpgcheck=1
        gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-LTB-project
      dest: /etc/yum.repos.d/ltb-project.repo
  when: ( ((ansible_distribution == "CentOS")  or (ansible_distribution == "Rocky") or (ansible_distribution == 'RedHat' )) and ( ( ansible_distribution_major_version == "8" ) or ( ansible_distribution_major_version == "9" ) ) )